"""Canary tests: what each role was shown, and what it was not.

This file enforces invariant 1. It works from the outside rather than by inspecting
`agents.py`: the loop is driven once, and then every `(system, prompt)` pair that reached
the backend is scanned through `LLMClient.prompts_for`, which `llm.py` provides for exactly
this purpose. A boundary can therefore only be broken by text actually reaching a model,
not by how a function is written.

**Never edit a test here to make a change pass.** A failure means the experiment is
leaking, and every run in `out/` produced under the leak is invalid. If a boundary
genuinely needs to move, that is an ADR in `docs/decisions/` and a commit that does
nothing else.

Two properties make these tests meaningful rather than decorative:

* The mock's outputs carry a per-call digest, so brief text, opinion text and query text
  are distinguishable strings rather than interchangeable placeholders. A test that
  searched for "MOCK:" would pass on anything.
* The scenario's `ground_truth_detail` is long, specific, and never generated by any
  model, so finding any of its phrases in a prompt can only mean it leaked.
"""

from __future__ import annotations

import random
import re

import pytest

from artsoc.agents import (
    Advisor,
    BoundaryViolation,
    CitizenPanelist,
    ExCommMember,
    IntelligenceOfficer,
    President,
    Theorist,
    assert_decontextualised,
    render_deliberation,
    render_situation,
)
from artsoc.config import RunConfig
from artsoc.llm import ROSTER_ENTRY, LLMClient, MockBackend, Role, role_marker
from artsoc.personas import load_excomm, load_registry
from artsoc.retrieval import get_retriever
from artsoc.schema import PresidentialQuery, public_statement_from
from artsoc.sim import build_panel
from artsoc.society import load_frame, sample_citizens
from artsoc.world import PerceptionFilter, build_world, load_scenario, public_events_from

SCENARIO_ID = "phase1_tel_dispersal_v1"

#: Phrases lifted from the scenario's host-only ground truth. None of these is ever
#: produced by a model, so any occurrence in a prompt is a leak and not a coincidence.
GROUND_TRUTH_PHRASES = (
    "HOST-ONLY",
    "survivability hedge, not launch preparation",
    "disarming first strike",
    "No warheads have been mated",
    "has not considered first use",
)


class LoopRun:
    """One hand-driven pass through the loop, holding everything it produced.

    `sim.py` will do this for real in the next block. Driving it here keeps the canary
    suite independent of orchestration: these boundaries must hold however the loop is
    assembled.
    """

    def __init__(
        self, seed: int = 7, k: int = 4, n_questions: int = 3,
        excluded: list[str] | None = None,
    ) -> None:
        self.scenario = load_scenario(SCENARIO_ID)
        rng = random.Random(seed)
        log = build_world(self.scenario)
        self.view, self.missed = PerceptionFilter(
            self.scenario.self_nation, self.scenario.perception
        ).view(log, self.scenario.now, rng)

        self.client = LLMClient(backend=MockBackend(), run_seed=seed)
        retriever = get_retriever("stub")

        self.forbidden = [
            self.scenario.self_nation,
            self.scenario.adversary_nation,
            "TEL",
            "dispersal",
            "garrison",
        ]

        self.intel = IntelligenceOfficer(self.client).brief(self.view, self.scenario.doctrine_card)

        president = President(self.client, self.scenario.doctrine_card)
        self.query = president.query(self.intel, self.forbidden)

        advisor = Advisor(self.client)
        self.questions = advisor.formulate(self.query, n_questions)

        excluded_set = set(excluded or [])
        self.personas = [p for p in load_registry() if p.persona_id not in excluded_set]
        self.opinions = []
        self.routing = []
        for question in self.questions:
            record = advisor.select(self.query, question, self.personas, k, rng)
            self.routing.append(record)
            for persona_id in record.selected:
                persona = next(p for p in self.personas if p.persona_id == persona_id)
                opinion, _block = Theorist(self.client, persona, "m2", retriever).opine(question)
                self.opinions.append(opinion)

        self.brief = advisor.synthesise(self.query, self.opinions, "full_range")
        self.coas = advisor.propose_coas(self.query, self.opinions)

        # The ExComm deliberation (ADR 0008). Driven here so the canary suite covers the
        # new roles however `sim.py` assembles them. Two rounds, so a round-2 prompt
        # contains round-1 statements — the inverted assertion below checks exactly that.
        self.lean_action, self.lean_coa_id, self.lean_reason = president.lean(
            self.intel, self.brief, self.coas
        )
        self.excomm = load_excomm()
        self.situation = render_situation(self.intel, self.view)
        self.deliberation = []
        self.deliberation_rounds = 0
        for round_no in (1, 2):
            self.deliberation_rounds = round_no
            transcript = render_deliberation(self.deliberation, self.excomm)
            for member in self.excomm:
                self.deliberation.append(
                    ExCommMember(self.client, member).contribute(
                        round_no, self.situation, self.brief, self.coas, transcript
                    )
                )
            president.chair(round_no, 3, render_deliberation(self.deliberation, self.excomm))

        self.action = president.decide(
            self.intel,
            self.brief,
            self.coas,
            deliberation_transcript=render_deliberation(self.deliberation, self.excomm),
        )

        # The citizen audience (ADR 0009). Driven here, strictly after the decision, so
        # the canary suite covers this role however `sim.py` assembles it — the same
        # reasoning the ExComm block above follows. A small n keeps the suite fast; the
        # boundary being tested does not depend on the sample size.
        frame = load_frame("us_1962")
        sample = sample_citizens(frame, 3, random.Random(seed))
        self.public_events = public_events_from(log.events)
        self.public_statement = public_statement_from(self.action)
        # Deliberately NOT `self.forbidden` (the scenario's proper nouns): the audience is
        # meant to see the anonymised nation labels and the public event's own content —
        # that is what `_render_public` shows it. What must never reach a citizen prompt is
        # the theorist/ExComm/ground-truth material below (ADR 0009).
        self.citizen_forbidden = [
            *(p.persona_id for p in self.personas),
            *(p.name for p in self.personas),
            *(o.position for o in self.opinions),
            *(o.reasoning for o in self.opinions),
            *(m.member_id for m in self.excomm),
            *(m.role_title for m in self.excomm),
            self.intel.summary,
            self.lean_reason,
        ]
        self.citizen_responses = [
            CitizenPanelist(self.client, citizen).respond(
                self.public_events, self.public_statement, self.citizen_forbidden
            )
            for citizen in sample.citizens
        ]

    def texts_for(self, role: Role) -> list[str]:
        """Every prompt this role saw, system and user concatenated."""
        return [f"{system}\n{prompt}" for system, prompt in self.client.prompts_for(role)]

    def all_texts(self) -> list[str]:
        return [t for role in Role for t in self.texts_for(role)]


@pytest.fixture(scope="module")
def run() -> LoopRun:
    return LoopRun()


# ---------------------------------------------------------------------------
# The host boundary. Ground truth exists so misperception can be scored, not so an
# agent can be correct.
# ---------------------------------------------------------------------------


def test_the_loop_actually_exercised_every_role(run: LoopRun) -> None:
    """A canary suite over an empty call log would pass while proving nothing."""
    for role in Role:
        assert run.texts_for(role), f"{role.value} was never called; the scan proves nothing"
    assert run.opinions, "no opinions were collected"


def test_ground_truth_reaches_no_prompt_of_any_role(run: LoopRun) -> None:
    """The host's truth must never reach any agent, at any step, in any role."""
    for text in run.all_texts():
        for phrase in GROUND_TRUTH_PHRASES:
            assert phrase.lower() not in text.lower(), f"ground truth leaked: {phrase!r}"


def test_ground_truth_is_present_in_the_scenario_being_tested(run: LoopRun) -> None:
    """Guards the test above: absent ground truth would make it vacuous."""
    truth = " ".join(run.scenario.ground_truth().values())
    for phrase in GROUND_TRUTH_PHRASES:
        assert phrase.lower() in truth.lower()


# ---------------------------------------------------------------------------
# The theorist boundary. Decontextualised elicitation, and no peer visibility.
# ---------------------------------------------------------------------------


def test_theorists_are_given_no_situation_context(run: LoopRun) -> None:
    """Invariant 1: a theorist reasoning about a crisis has no standing to know of it."""
    forbidden = [
        run.scenario.self_nation,
        run.scenario.adversary_nation,
        run.scenario.events[0].description[:60],
        run.scenario.doctrine_card.doctrine[:60],
        run.scenario.doctrine_card.collection_bias[:60],
    ]
    for text in run.texts_for(Role.THEORIST):
        for token in forbidden:
            assert token.lower() not in text.lower(), f"theorist prompt leaked {token[:40]!r}"


def test_theorists_never_see_intelligence_reporting(run: LoopRun) -> None:
    """A theorist with collection access is an advisor, not an analytical respondent."""
    for text in run.texts_for(Role.THEORIST):
        assert run.intel.summary not in text
        assert run.intel.assessed_activity not in text


def test_a_theorist_sees_no_other_persona(run: LoopRun) -> None:
    """Peer visibility makes apparent consensus a herding artifact of call ordering."""
    names = [p.name for p in run.personas]
    for text in run.texts_for(Role.THEORIST):
        present = [n for n in names if n in text]
        assert len(present) <= 1, f"a theorist prompt named {len(present)} personas: {present}"


def test_a_theorist_never_sees_another_theorists_answer(run: LoopRun) -> None:
    """Later personas must not anchor on earlier ones."""
    answers = {o.position for o in run.opinions} | {o.reasoning for o in run.opinions}
    for text in run.texts_for(Role.THEORIST):
        for answer in answers:
            assert answer not in text, "a theorist was shown another theorist's answer"


def test_every_theorist_prompt_carries_a_record_or_declares_it_has_none(run: LoopRun) -> None:
    """ADR 0001: the marker must reach the user prompt or the escape hatch cannot fire."""
    for _system, prompt in run.client.prompts_for(Role.THEORIST):
        assert "RECORD:" in prompt


def test_the_escape_hatch_is_not_pinned_at_zero(run: LoopRun) -> None:
    """A near-zero out-of-record rate means personas are extrapolating past their record.

    CLAUDE.md is explicit that this is a warning rather than a success, so it is asserted
    here: a run in which no persona ever declines is a broken run, not a clean one.
    """
    declines = sum(1 for o in run.opinions if o.out_of_record)
    assert 0 < declines < len(run.opinions)


def test_grounding_is_never_claimed_by_a_stub_run(run: LoopRun) -> None:
    """Invariant 4: a stub run must not be capable of being read as corpus-grounded."""
    assert get_retriever("stub").grounded is False


# ---------------------------------------------------------------------------
# The advisor boundary. Compression of expert opinion, not a second analytic layer.
# ---------------------------------------------------------------------------


def test_the_advisor_never_sees_intelligence_reporting(run: LoopRun) -> None:
    """Otherwise the brief becomes a second, unlogged analytic layer."""
    for role in (Role.ADVISOR_QUESTIONS, Role.ADVISOR_SYNTHESIS):
        for text in run.texts_for(role):
            assert run.intel.summary not in text
            assert run.intel.assessed_activity not in text
            for alternative in run.intel.alternative_explanations:
                assert alternative not in text


def test_the_advisor_never_sees_collection_output_or_doctrine(run: LoopRun) -> None:
    """The Advisor has no collection access; the query is not a channel for one."""
    forbidden = [
        run.scenario.self_nation,
        run.scenario.adversary_nation,
        run.scenario.events[0].description[:60],
        run.scenario.doctrine_card.collection_bias[:60],
    ]
    for role in (Role.ADVISOR_QUESTIONS, Role.ADVISOR_SYNTHESIS):
        for text in run.texts_for(role):
            for token in forbidden:
                assert token.lower() not in text.lower(), f"advisor prompt leaked {token[:40]!r}"


def test_a_query_carrying_situational_detail_is_refused() -> None:
    """The guard must raise rather than scrub: a cleaned-up leak is a leak nobody finds."""
    with pytest.raises(BoundaryViolation):
        assert_decontextualised(
            "What should we do about Nation B's missile dispersal?",
            ["Nation B", "dispersal"],
            where="test",
        )
    # And must not fire on a genuinely decontextualised question.
    assert_decontextualised(
        "What makes a deterrent threat credible?", ["Nation B", "dispersal"], where="test"
    )


def test_the_president_cannot_smuggle_context_past_the_guard(run: LoopRun) -> None:
    """The guard runs on the real path, not only in isolation."""
    president = President(run.client, run.scenario.doctrine_card)
    leaky = PresidentialQuery(text="How should we read Nation B's behaviour?", concerns=[])
    with pytest.raises(BoundaryViolation):
        assert_decontextualised(leaky.text, run.forbidden, where="the presidential query")
    # The query the President actually produced passes the same guard.
    assert_decontextualised(run.query.text, run.forbidden, where="the presidential query")
    assert president is not None


# ---------------------------------------------------------------------------
# The presidential boundary. The compression is a modelled step, so both sides of it
# must not be visible at once.
# ---------------------------------------------------------------------------


def test_the_president_never_sees_raw_theorist_output(run: LoopRun) -> None:
    """What the compression drops is itself a finding; showing both sides would erase it."""
    for text in run.texts_for(Role.PRESIDENT_DECISION):
        for opinion in run.opinions:
            assert opinion.position not in text
            assert opinion.reasoning not in text
            assert opinion.persona_name not in text


def test_the_president_does_see_the_advisor_brief(run: LoopRun) -> None:
    """Guards the test above: a President shown nothing would pass it trivially."""
    texts = run.texts_for(Role.PRESIDENT_DECISION)
    assert any(run.brief.summary in t for t in texts)


def test_the_advisor_sees_full_opinions_to_write_the_coas(run: LoopRun) -> None:
    """The Advisor's *input* legitimately contains full opinion text — invariant 1
    restricts what the President sees, not what the Advisor sees, and this is the same
    thing `synthesise` already does to write the brief. Guards the next test: a COA
    proposal step that saw nothing could not possibly cite anything real."""
    texts = run.texts_for(Role.ADVISOR_COAS)
    assert texts, "COA proposal never ran; the scan proves nothing"
    assert any(
        opinion.position in text for opinion in run.opinions for text in texts
    ), "the Advisor was shown no real opinion text; its citations would be fabricated"


def test_a_coas_rationale_never_quotes_raw_theorist_output(run: LoopRun) -> None:
    """ADR 0006: a course of action is the Advisor's own case, cited by id — never a
    theorist's position or reasoning reproduced verbatim. Checked on the Advisor's
    *output* (what it wrote), not its input (which the test above confirms is the full
    opinions, exactly as `synthesise` already receives)."""
    assert run.coas, "no courses of action were produced; the scan proves nothing"
    for coa in run.coas:
        for opinion in run.opinions:
            assert opinion.position not in coa.rationale
            assert opinion.reasoning not in coa.rationale


def test_the_presidents_decision_prompt_shows_coas_but_not_raw_opinions(
    run: LoopRun,
) -> None:
    """The President reads the Advisor's case for each option, never the opinions behind
    it — the same boundary `test_the_president_never_sees_raw_theorist_output` already
    checks against the brief, checked again against this new surface."""
    texts = run.texts_for(Role.PRESIDENT_DECISION)
    assert any(coa.rationale in t for coa in run.coas for t in texts), (
        "guards against a vacuous pass: the President must actually be shown the COAs"
    )
    for text in texts:
        for opinion in run.opinions:
            assert opinion.position not in text
            assert opinion.reasoning not in text


def test_the_three_coas_are_distinct_actions(run: LoopRun) -> None:
    """Three identical proposals is not three courses of action."""
    assert len(run.coas) == 3
    assert len({coa.action for coa in run.coas}) == 3


def test_the_chosen_action_matches_one_of_the_offered_coas(run: LoopRun) -> None:
    """The action taken is the offered course's action, not a free-floating choice."""
    matching = [
        coa for coa in run.coas
        if coa.coa_id == run.action.chosen_coa_id and coa.action == run.action.action
    ]
    assert len(matching) == 1


def test_the_president_writing_the_query_has_not_yet_seen_any_opinion(run: LoopRun) -> None:
    """The query is asked before the panel is consulted and cannot reflect it."""
    for text in run.texts_for(Role.PRESIDENT_QUERY):
        for opinion in run.opinions:
            assert opinion.position not in text


# ---------------------------------------------------------------------------
# The ExComm deliberation (ADR 0008). The committee is the first role set permitted peer
# visibility, and it sees the anonymised situation. Everything it may NOT see is asserted
# explicitly here, and the one thing it MUST see — the prior rounds of its own debate — is
# the inverted assertion that documents the exception as deliberate.
# ---------------------------------------------------------------------------


def test_an_excomm_member_sees_the_prior_rounds_of_debate(run: LoopRun) -> None:
    """The exception, made explicit. Peer visibility is forbidden for theorists because it
    turns consensus into a herding artifact; for a deliberative committee it is the point.
    A round-2 prompt must contain round-1 statements or the debate is theatre."""
    round_one = [s.statement for s in run.deliberation if s.round == 1 and not s.abstained]
    assert round_one, "no round-1 statements were made; the scan proves nothing"
    round_two_texts = [
        t for t in run.texts_for(Role.EXCOMM_MEMBER) if "[[ROUND:2]]" in t
    ]
    assert round_two_texts, "no round-2 turns ran"
    assert any(
        stmt in t for stmt in round_one for t in round_two_texts
    ), "a round-2 member was not shown what round 1 said"


def test_an_excomm_member_never_sees_raw_theorist_opinions(run: LoopRun) -> None:
    """The committee sees the Advisor's brief and the three COAs — the same compression the
    President sees — never the opinions behind them."""
    for text in run.texts_for(Role.EXCOMM_MEMBER):
        for opinion in run.opinions:
            assert opinion.position not in text
            assert opinion.reasoning not in text
            assert opinion.persona_name not in text


def test_the_excomm_never_sees_ground_truth(run: LoopRun) -> None:
    """Already covered by the all-roles sweep, asserted again because this role is newly
    situation-aware and the boundary is the one that must never move."""
    for text in run.texts_for(Role.EXCOMM_MEMBER) + run.texts_for(Role.PRESIDENT_CHAIR):
        for phrase in GROUND_TRUTH_PHRASES:
            assert phrase.lower() not in text.lower()


def test_no_real_committee_name_reaches_any_prompt(run: LoopRun) -> None:
    """The roster is 1962-shaped, not nominal: the real names in docs/excomm/roster-key.md
    must not appear in any prompt of any role, the way the scenario keeps 'Cuba' out."""
    import re as _re
    from pathlib import Path

    key = (Path(__file__).resolve().parents[1] / "docs" / "excomm" / "roster-key.md").read_text()
    # Each figure cell is a full name; the leak indicator is the full name or the surname
    # (last token). Bare given names — "Robert", "George" — are deliberately not checked:
    # they collide with theorist persona names ("Robert Jervis", "Alexander George") that
    # legitimately appear in routing prompts.
    names: set[str] = set()
    for line in key.splitlines():
        if line.startswith("| `"):
            cells = [c.strip() for c in line.strip("|").split("|")]
            if len(cells) >= 3 and not cells[0].startswith("---") and cells[2]:
                full = cells[2]
                if full.lower().startswith("figure"):
                    continue
                names.add(full)
                names.add(full.replace(".", "").split()[-1])  # surname
    assert len(names) >= 15, "anti-vacuity: full names and surnames must have been extracted"
    for text in run.all_texts():
        hits = sorted(n for n in names if _re.search(rf"\b{_re.escape(n)}\b", text))
        assert hits == [], f"a real committee name reached a prompt: {hits}"


def test_the_secret_lean_reaches_no_prompt_of_any_role(run: LoopRun) -> None:
    """The President's private prior is recorded and never re-prompted — not even into the
    President's own later decision prompt. Scanned the way ground truth is."""
    assert run.lean_reason, "anti-vacuity: a lean reasoning string must have been produced"
    for text in run.all_texts():
        assert run.lean_reason not in text, "the secret lean's reasoning leaked into a prompt"
    # The decision prompt shows the debate; it must not show the lean.
    decision_texts = run.texts_for(Role.PRESIDENT_DECISION)
    assert any(
        s.statement and s.statement in t for s in run.deliberation for t in decision_texts
    ), "guards against a vacuous pass: the decision prompt must show the concluded debate"
    for text in decision_texts:
        assert run.lean_reason not in text


def test_the_lean_and_chair_never_see_raw_theorist_opinions(run: LoopRun) -> None:
    """The lean sees the brief and the COAs; the chair sees only the transcript. Neither
    sees the opinions behind the compression."""
    for role in (Role.PRESIDENT_LEAN, Role.PRESIDENT_CHAIR):
        for text in run.texts_for(role):
            for opinion in run.opinions:
                assert opinion.position not in text
                assert opinion.reasoning not in text


# ---------------------------------------------------------------------------
# The citizen audience (ADR 0009). An outcome measure: it runs strictly after the
# decision, sees only the publicly known event and the President's action, and nothing it
# produces returns to any earlier role.
# ---------------------------------------------------------------------------


def test_no_citizen_prompt_carries_a_theorist_name_opinion_or_citation(run: LoopRun) -> None:
    """The audience never sees the panel, its positions, or what they cited."""
    for text in run.texts_for(Role.CITIZEN):
        for persona in run.personas:
            assert persona.persona_id not in text
            assert persona.name not in text
        for opinion in run.opinions:
            assert opinion.position not in text
            assert opinion.reasoning not in text
            for citation in opinion.citations:
                assert citation not in text


def test_no_citizen_prompt_carries_the_excomm_transcript_or_a_member_label(run: LoopRun) -> None:
    """The debate is the point for the ExComm; it must not reach the audience at all."""
    for text in run.texts_for(Role.CITIZEN):
        for member in run.excomm:
            assert member.member_id not in text
            assert member.role_title not in text
        for statement in run.deliberation:
            if statement.statement:
                assert statement.statement not in text


def test_no_citizen_prompt_carries_the_secret_lean(run: LoopRun) -> None:
    """Scanned the way the President's own decision prompt is scanned for it."""
    for text in run.texts_for(Role.CITIZEN):
        assert run.lean_reason not in text


def test_a_citizen_response_never_reaches_any_earlier_roles_prompt(run: LoopRun) -> None:
    """The mirror image of the secret-lean test above: the audience runs last, so its own
    output must never leak *backward* into a role that ran before it — the concrete form
    of 'nothing it produces returns to the President'."""
    rationales = [r.rationale for r in run.citizen_responses if r.rationale]
    assert rationales, "anti-vacuity: no citizen produced a rationale to scan for"
    non_citizen_roles = [role for role in Role if role is not Role.CITIZEN]
    for role in non_citizen_roles:
        for text in run.texts_for(role):
            for rationale in rationales:
                assert rationale not in text
            for citizen in run.citizen_responses:
                assert citizen.citizen_id not in text


def test_a_planted_forbidden_token_makes_a_citizen_call_raise_not_scrub(run: LoopRun) -> None:
    """The canary discipline: a guard that is never shown to fail is not evidence. Plants
    one of the run's own theorist names as a forbidden token for a real citizen from this
    loop and confirms the call raises `BoundaryViolation` rather than continuing on a
    scrubbed prompt. The revert half of this discipline — the same setup with the token
    removed succeeding — is `tests/test_society.py::
    test_with_no_forbidden_token_planted_the_same_call_succeeds`, against the same
    `CitizenPanelist.respond`."""
    from artsoc.schema import ActionType, PublicStatement

    statement = PublicStatement(action=ActionType.NO_ACTION, justification="MOCK:")
    citizen = load_frame("us_1962")
    planted = sample_citizens(citizen, 1, random.Random(1)).citizens[0]
    panelist = CitizenPanelist(run.client, planted)

    # `build_citizen_identity_prompt` renders underscores as spaces, so the forbidden
    # token must match what actually reaches the prompt, not the raw stratum value.
    with pytest.raises(BoundaryViolation, match="citizen"):
        panelist.respond([], statement, forbidden_tokens=[planted.region.replace("_", " ")])


# ---------------------------------------------------------------------------
# Role separation at the choke point.
# ---------------------------------------------------------------------------


def test_every_prompt_carries_its_own_role_marker_and_no_other(run: LoopRun) -> None:
    """Role differentiation must live in the prompt, where these tests can see it."""
    for role in Role:
        for system, _prompt in run.client.prompts_for(role):
            assert role_marker(role) in system
            for other in Role:
                if other is not role:
                    assert role_marker(other) not in system


def test_only_the_io_and_the_excomm_are_shown_collection_output(run: LoopRun) -> None:
    """Collection output is the IO's input; the ExComm is also shown it (ADR 0008).

    Changed from "the IO alone" when the ExComm was added: the committee is a briefed
    deliberative body convened over the specific crisis, so it sees the anonymised
    situation — the intel brief and the perceived events — the same way the President does.
    It still never sees `ground_truth_detail`. No other role is shown the signature.
    """
    signature = run.scenario.events[0].observable_signature[0]
    seen_in = {role for role in Role if any(signature in t for t in run.texts_for(role))}
    assert seen_in == {Role.INTEL_OFFICER, Role.EXCOMM_MEMBER}


# ---------------------------------------------------------------------------
# Advisor-chosen routing. Deciding whom to consult is a modelled social act, so the
# Advisor must be able to see who exists — and still nothing about the situation.
# ---------------------------------------------------------------------------


def test_the_advisor_selects_without_ever_seeing_the_situation(run: LoopRun) -> None:
    """Selection is the newest channel into the Advisor, so it is the newest leak surface."""
    forbidden = [
        run.scenario.self_nation,
        run.scenario.adversary_nation,
        run.scenario.events[0].description[:60],
        run.scenario.doctrine_card.collection_bias[:60],
    ]
    texts = run.texts_for(Role.ADVISOR_SELECTION)
    assert texts, "advisor selection never ran; the scan proves nothing"
    for text in texts:
        assert run.intel.summary not in text
        for token in forbidden:
            assert token.lower() not in text.lower(), f"selection prompt leaked {token[:40]!r}"


def test_the_selection_prompt_shows_the_roster_it_is_choosing_from(run: LoopRun) -> None:
    """The roster must be in the prompt, not an argument, or no test can see who was offered."""
    for _system, prompt in run.client.prompts_for(Role.ADVISOR_SELECTION):
        offered = set(ROSTER_ENTRY.findall(prompt))
        assert offered, "no roster markers in the selection prompt"
        assert offered <= {p.persona_id for p in run.personas}


def test_the_advisor_records_why_it_chose(run: LoopRun) -> None:
    """A selection with no stated reason is not a modelled decision, just an outcome."""
    for record in run.routing:
        assert record.mode == "advisor"
        assert record.rationale.strip(), "selection carries no rationale"
        assert record.roster, "selection did not record who was on offer"


def test_a_persona_the_advisor_invents_is_never_consulted(run: LoopRun) -> None:
    """A model naming someone off-roster must be refused, or exclusion means nothing."""
    for record in run.routing:
        assert set(record.selected) <= set(record.roster)
        assert not set(record.hallucinated) & set(record.selected)


# ---------------------------------------------------------------------------
# Forced exclusion. "As though they never existed" is a claim about prompts, not
# about routing outcomes.
# ---------------------------------------------------------------------------


def test_an_excluded_theorist_reaches_no_prompt_of_any_role() -> None:
    """The intervention is that the world never had them, not that nobody picked them.

    Checked on the id and the display name, in every prompt of every role. If the name
    survived anywhere the Advisor could still be influenced by knowing they exist, and the
    exclusion contrast would be measuring something weaker than it claims.
    """
    excluded = "schelling"
    run = LoopRun(excluded=[excluded])
    persona = next(p for p in load_registry() if p.persona_id == excluded)

    assert run.opinions, "no opinions collected; the scan proves nothing"
    for text in run.all_texts():
        assert excluded not in text.lower()
        assert persona.name.lower() not in text.lower()

    for record in run.routing:
        assert excluded not in record.roster
        assert excluded not in record.selected
    assert excluded not in {o.persona_id for o in run.opinions}


def test_the_surviving_panel_is_exactly_one_smaller() -> None:
    """A silently-unchanged panel would make every exclusion arm a duplicate of baseline."""
    full = LoopRun()
    minus_one = LoopRun(excluded=["schelling"])
    assert len(minus_one.personas) == len(full.personas) - 1
    assert {p.persona_id for p in full.personas} - {p.persona_id for p in minus_one.personas} == {
        "schelling"
    }


def test_excluding_an_unknown_theorist_raises_rather_than_running() -> None:
    """An arm excluding someone who does not exist would run and duplicate baseline."""
    with pytest.raises(ValueError):
        build_panel(RunConfig(arm="typo", excluded_personas=["schelibg"]), random.Random(0))


def test_the_guard_matches_whole_words_not_substrings() -> None:
    """A guard that fires on ordinary prose gets switched off, which is worse than useless.

    The scenario contributes the token "tel" from the event label `tel_dispersal`. Under
    substring matching that fired inside "intelligence", which aborted a perfectly clean
    presidential query on the first live run. The mock never produced ordinary English, so
    only a live call could surface it.
    """
    forbidden = ["Nation A", "Nation B", "TEL", "dispersal", "garrison"]

    # Ordinary prose that merely contains the letters must pass.
    for clean in (
        "How should intelligence uncertainty shape a response?",
        "What does satellite coverage imply for warning time?",
        "Is telling an adversary your red lines stabilising?",
    ):
        assert_decontextualised(clean, forbidden, where="test")

    # The tokens themselves, as words, must still be caught.
    for leak in (
        "What should we infer from the TEL movement?",
        "How should we read a dispersal of mobile launchers?",
        "What does Nation B intend?",
    ):
        with pytest.raises(BoundaryViolation):
            assert_decontextualised(leak, forbidden, where="test")


def test_no_prompt_uses_a_real_persona_id_as_a_worked_example() -> None:
    """An example id is still that persona's name appearing in a prompt.

    A format example written as `["brodie", "schelling"]` put an excluded theorist back
    into the selection prompt, which is exactly what forced exclusion is supposed to
    prevent. Examples must use ids that belong to nobody.

    Both roles legitimately list real ids and names in their *data* section — the roster
    for selection, the collected opinions for COAs (`test_the_advisor_sees_full_opinions_
    to_write_the_coas` guards that this stays true). A blanket scan of the whole prompt
    would flag that legitimate data as if it were a leak. So this checks only the
    *instructions* tail of each prompt — the format rules and worked examples that follow
    the data — which should never reference a persona at all. The same mistake recurred
    there once already: `ADVISOR_COAS`'s citation-format example was first written as
    "q0:schelling" on the first live run of ADR 0006.
    """
    run = LoopRun()
    real_ids = {p.persona_id for p in load_registry()}
    real_names = {p.name.lower() for p in load_registry()}
    # Where each role's instructions begin, right after its data section ends.
    instructions_start = {
        Role.ADVISOR_SELECTION: "Select exactly",
        Role.ADVISOR_COAS: "AVAILABLE ACTIONS",
    }
    for role, marker in instructions_start.items():
        for _system, prompt in run.client.prompts_for(role):
            assert marker in prompt, f"{role.value} is missing its instructions marker {marker!r}"
            instructions = prompt.split(marker, 1)[1].lower()
            leaked_ids = {
                pid for pid in real_ids if re.search(rf"\b{re.escape(pid)}\b", instructions)
            }
            leaked_names = {name for name in real_names if name in instructions}
            assert not leaked_ids, (
                f"{role.value} instructions used real id(s) {leaked_ids} as an example"
            )
            assert not leaked_names, (
                f"{role.value} instructions used real name(s) {leaked_names} as an example"
            )
