"""Canary tests: what each role was shown, and what it was not.

This file enforces invariant 1. It works from the outside rather than by inspecting
`agents.py`: the loop is driven once, and then every `(system, prompt)` pair that reached
the backend is scanned through `LLMClient.prompts_for`, which `llm.py` provides for exactly
this purpose. A boundary can therefore only be broken by text actually reaching a model,
not by how a function is written.

**Never edit a test here to make a change pass.** A failure means the experiment is
leaking, and every run in `out/` produced under the leak is invalid. If a boundary
genuinely needs to move, that is an ADR in `docs/decisions/` and a commit that does
nothing else.

Two properties make these tests meaningful rather than decorative:

* The mock's outputs carry a per-call digest, so brief text, opinion text and query text
  are distinguishable strings rather than interchangeable placeholders. A test that
  searched for "MOCK:" would pass on anything.
* The scenario's `ground_truth_detail` is long, specific, and never generated by any
  model, so finding any of its phrases in a prompt can only mean it leaked.
"""

from __future__ import annotations

import random

import pytest

from artsoc.agents import (
    Advisor,
    BoundaryViolation,
    IntelligenceOfficer,
    President,
    Theorist,
    assert_decontextualised,
)
from artsoc.llm import LLMClient, MockBackend, Role, role_marker
from artsoc.personas import load_registry, route
from artsoc.retrieval import get_retriever
from artsoc.schema import PresidentialQuery
from artsoc.world import PerceptionFilter, build_world, load_scenario

SCENARIO_ID = "phase1_tel_dispersal_v1"

#: Phrases lifted from the scenario's host-only ground truth. None of these is ever
#: produced by a model, so any occurrence in a prompt is a leak and not a coincidence.
GROUND_TRUTH_PHRASES = (
    "HOST-ONLY",
    "survivability hedge, not launch preparation",
    "disarming first strike",
    "No warheads have been mated",
    "has not considered first use",
)


class LoopRun:
    """One hand-driven pass through the loop, holding everything it produced.

    `sim.py` will do this for real in the next block. Driving it here keeps the canary
    suite independent of orchestration: these boundaries must hold however the loop is
    assembled.
    """

    def __init__(self, seed: int = 7, k: int = 4, n_questions: int = 3) -> None:
        self.scenario = load_scenario(SCENARIO_ID)
        rng = random.Random(seed)
        log = build_world(self.scenario)
        self.view, self.missed = PerceptionFilter(
            self.scenario.self_nation, self.scenario.perception
        ).view(log, self.scenario.now, rng)

        self.client = LLMClient(backend=MockBackend(), run_seed=seed)
        retriever = get_retriever("stub")

        self.forbidden = [
            self.scenario.self_nation,
            self.scenario.adversary_nation,
            "TEL",
            "dispersal",
            "garrison",
        ]

        self.intel = IntelligenceOfficer(self.client).brief(self.view, self.scenario.doctrine_card)

        president = President(self.client, self.scenario.doctrine_card)
        self.query = president.query(self.intel, self.forbidden)

        advisor = Advisor(self.client)
        self.questions = advisor.formulate(self.query, n_questions)

        self.personas = load_registry()
        self.opinions = []
        self.routing = []
        for question in self.questions:
            record = route(question, self.personas, k=k, rng=rng)
            self.routing.append(record)
            for persona_id in record.selected:
                persona = next(p for p in self.personas if p.persona_id == persona_id)
                opinion, _block = Theorist(self.client, persona, "m2", retriever).opine(question)
                self.opinions.append(opinion)

        self.brief = advisor.synthesise(self.query, self.opinions, "full_range")
        self.action = president.decide(self.intel, self.brief)

    def texts_for(self, role: Role) -> list[str]:
        """Every prompt this role saw, system and user concatenated."""
        return [f"{system}\n{prompt}" for system, prompt in self.client.prompts_for(role)]

    def all_texts(self) -> list[str]:
        return [t for role in Role for t in self.texts_for(role)]


@pytest.fixture(scope="module")
def run() -> LoopRun:
    return LoopRun()


# ---------------------------------------------------------------------------
# The host boundary. Ground truth exists so misperception can be scored, not so an
# agent can be correct.
# ---------------------------------------------------------------------------


def test_the_loop_actually_exercised_every_role(run: LoopRun) -> None:
    """A canary suite over an empty call log would pass while proving nothing."""
    for role in Role:
        assert run.texts_for(role), f"{role.value} was never called; the scan proves nothing"
    assert run.opinions, "no opinions were collected"


def test_ground_truth_reaches_no_prompt_of_any_role(run: LoopRun) -> None:
    """The host's truth must never reach any agent, at any step, in any role."""
    for text in run.all_texts():
        for phrase in GROUND_TRUTH_PHRASES:
            assert phrase.lower() not in text.lower(), f"ground truth leaked: {phrase!r}"


def test_ground_truth_is_present_in_the_scenario_being_tested(run: LoopRun) -> None:
    """Guards the test above: absent ground truth would make it vacuous."""
    truth = " ".join(run.scenario.ground_truth().values())
    for phrase in GROUND_TRUTH_PHRASES:
        assert phrase.lower() in truth.lower()


# ---------------------------------------------------------------------------
# The theorist boundary. Decontextualised elicitation, and no peer visibility.
# ---------------------------------------------------------------------------


def test_theorists_are_given_no_situation_context(run: LoopRun) -> None:
    """Invariant 1: a theorist reasoning about a crisis has no standing to know of it."""
    forbidden = [
        run.scenario.self_nation,
        run.scenario.adversary_nation,
        run.scenario.events[0].description[:60],
        run.scenario.doctrine_card.doctrine[:60],
        run.scenario.doctrine_card.collection_bias[:60],
    ]
    for text in run.texts_for(Role.THEORIST):
        for token in forbidden:
            assert token.lower() not in text.lower(), f"theorist prompt leaked {token[:40]!r}"


def test_theorists_never_see_intelligence_reporting(run: LoopRun) -> None:
    """A theorist with collection access is an advisor, not an analytical respondent."""
    for text in run.texts_for(Role.THEORIST):
        assert run.intel.summary not in text
        assert run.intel.assessed_activity not in text


def test_a_theorist_sees_no_other_persona(run: LoopRun) -> None:
    """Peer visibility makes apparent consensus a herding artifact of call ordering."""
    names = [p.name for p in run.personas]
    for text in run.texts_for(Role.THEORIST):
        present = [n for n in names if n in text]
        assert len(present) <= 1, f"a theorist prompt named {len(present)} personas: {present}"


def test_a_theorist_never_sees_another_theorists_answer(run: LoopRun) -> None:
    """Later personas must not anchor on earlier ones."""
    answers = {o.position for o in run.opinions} | {o.reasoning for o in run.opinions}
    for text in run.texts_for(Role.THEORIST):
        for answer in answers:
            assert answer not in text, "a theorist was shown another theorist's answer"


def test_every_theorist_prompt_carries_a_record_or_declares_it_has_none(run: LoopRun) -> None:
    """ADR 0001: the marker must reach the user prompt or the escape hatch cannot fire."""
    for _system, prompt in run.client.prompts_for(Role.THEORIST):
        assert "RECORD:" in prompt


def test_the_escape_hatch_is_not_pinned_at_zero(run: LoopRun) -> None:
    """A near-zero out-of-record rate means personas are extrapolating past their record.

    CLAUDE.md is explicit that this is a warning rather than a success, so it is asserted
    here: a run in which no persona ever declines is a broken run, not a clean one.
    """
    declines = sum(1 for o in run.opinions if o.out_of_record)
    assert 0 < declines < len(run.opinions)


def test_grounding_is_never_claimed_by_a_stub_run(run: LoopRun) -> None:
    """Invariant 4: a stub run must not be capable of being read as corpus-grounded."""
    assert get_retriever("stub").grounded is False


# ---------------------------------------------------------------------------
# The advisor boundary. Compression of expert opinion, not a second analytic layer.
# ---------------------------------------------------------------------------


def test_the_advisor_never_sees_intelligence_reporting(run: LoopRun) -> None:
    """Otherwise the brief becomes a second, unlogged analytic layer."""
    for role in (Role.ADVISOR_QUESTIONS, Role.ADVISOR_SYNTHESIS):
        for text in run.texts_for(role):
            assert run.intel.summary not in text
            assert run.intel.assessed_activity not in text
            for alternative in run.intel.alternative_explanations:
                assert alternative not in text


def test_the_advisor_never_sees_collection_output_or_doctrine(run: LoopRun) -> None:
    """The Advisor has no collection access; the query is not a channel for one."""
    forbidden = [
        run.scenario.self_nation,
        run.scenario.adversary_nation,
        run.scenario.events[0].description[:60],
        run.scenario.doctrine_card.collection_bias[:60],
    ]
    for role in (Role.ADVISOR_QUESTIONS, Role.ADVISOR_SYNTHESIS):
        for text in run.texts_for(role):
            for token in forbidden:
                assert token.lower() not in text.lower(), f"advisor prompt leaked {token[:40]!r}"


def test_a_query_carrying_situational_detail_is_refused() -> None:
    """The guard must raise rather than scrub: a cleaned-up leak is a leak nobody finds."""
    with pytest.raises(BoundaryViolation):
        assert_decontextualised(
            "What should we do about Nation B's missile dispersal?",
            ["Nation B", "dispersal"],
            where="test",
        )
    # And must not fire on a genuinely decontextualised question.
    assert_decontextualised(
        "What makes a deterrent threat credible?", ["Nation B", "dispersal"], where="test"
    )


def test_the_president_cannot_smuggle_context_past_the_guard(run: LoopRun) -> None:
    """The guard runs on the real path, not only in isolation."""
    president = President(run.client, run.scenario.doctrine_card)
    leaky = PresidentialQuery(text="How should we read Nation B's behaviour?", concerns=[])
    with pytest.raises(BoundaryViolation):
        assert_decontextualised(leaky.text, run.forbidden, where="the presidential query")
    # The query the President actually produced passes the same guard.
    assert_decontextualised(run.query.text, run.forbidden, where="the presidential query")
    assert president is not None


# ---------------------------------------------------------------------------
# The presidential boundary. The compression is a modelled step, so both sides of it
# must not be visible at once.
# ---------------------------------------------------------------------------


def test_the_president_never_sees_raw_theorist_output(run: LoopRun) -> None:
    """What the compression drops is itself a finding; showing both sides would erase it."""
    for text in run.texts_for(Role.PRESIDENT_DECISION):
        for opinion in run.opinions:
            assert opinion.position not in text
            assert opinion.reasoning not in text
            assert opinion.persona_name not in text


def test_the_president_does_see_the_advisor_brief(run: LoopRun) -> None:
    """Guards the test above: a President shown nothing would pass it trivially."""
    texts = run.texts_for(Role.PRESIDENT_DECISION)
    assert any(run.brief.summary in t for t in texts)


def test_the_president_writing_the_query_has_not_yet_seen_any_opinion(run: LoopRun) -> None:
    """The query is asked before the panel is consulted and cannot reflect it."""
    for text in run.texts_for(Role.PRESIDENT_QUERY):
        for opinion in run.opinions:
            assert opinion.position not in text


# ---------------------------------------------------------------------------
# Role separation at the choke point.
# ---------------------------------------------------------------------------


def test_every_prompt_carries_its_own_role_marker_and_no_other(run: LoopRun) -> None:
    """Role differentiation must live in the prompt, where these tests can see it."""
    for role in Role:
        for system, _prompt in run.client.prompts_for(role):
            assert role_marker(role) in system
            for other in Role:
                if other is not role:
                    assert role_marker(other) not in system


def test_the_intelligence_officer_is_the_only_role_shown_collection_output(run: LoopRun) -> None:
    """Collection output is the IO's input and nobody else's."""
    signature = run.scenario.events[0].observable_signature[0]
    seen_in = {role for role in Role if any(signature in t for t in run.texts_for(role))}
    assert seen_in == {Role.INTEL_OFFICER}
